version: '3.3'
networks: 
  web:
    external: true
services:
  leechbox:
    ports:
      - '9090:9090'
    hostname: leechbox.docker
    build: .
    image: leechbox
    container_name: leechbox
    networks:
      - web
    environment:
      - PUID=1000
      - GUID=1000
    user: 1000:1000
    volumes:
      - $PWD/appdata:/config
     # - $HOME/downloads/blackhole:/downloads
